version: '3'
services:
  app:
    build: .
    image: fletar
    command: python main.py
    ports:
      - "80:8000"
    volumes:
      - ./app:/app
    restart: always
    labels:
      - "traefik.http.routers.fletar.rule=Host(`fletar.apps.devecoop.coop.ar`)"
      - "traefik.http.routers.fletar.tls=true"
      - "traefik.http.routers.fletar.tls.certresolver=letsencrypt"
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
    networks:
      - proxy
      - default
    environment:
      - SPREADSHEET_URL=${SPREADSHEET_URL}
networks:
   proxy:
     external: true

